
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dough_fin_be_development

test:
  <<: *default
  database: dough_fin_be_test
  host: localhost
  username: <%= ENV['DB_USERNAME'] || `whoami`.strip %>
  password: <%= ENV['DB_PASSWORD'] || '' %>

production:
  <<: *default
  url: <%= Rails.application.credentials.DATABASE_URL %>
